In [3]:
import pandas as pd
import numpy as np

In [4]:
FILE_PATH = r"./data/IPL.csv"

In [5]:
print(f"-"*50)
print(f"Reading IPL Data")
ipl_data = pd.read_csv(FILE_PATH, low_memory=False)
print(f"Read IPL Data with shape {ipl_data.shape}")
print(f"Columns found are \n {ipl_data.columns}")
print(f"-"*50)

--------------------------------------------------
Reading IPL Data
Read IPL Data with shape (278205, 64)
Columns found are
 Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs',
       'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter',
       'striker_out'],
      dtype='str')
--------------------------------------------------

In [6]:
print(f"-"*50)
print(ipl_data.info())
print(f"-"*50)

--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   date               278205 non-null  str
 3   match_type         278205 non-null  str
 4   event_name         278205 non-null  str
 5   innings            278205 non-null  int64
 6   batting_team       278205 non-null  str
 7   bowling_team       278205 non-null  str
 8   over               278205 non-null  int64
 9   ball               278205 non-null  int64
 10  ball_no            278205 non-null  float64
 11  batter             278205 non-null  str
 12  bat_pos            278205 non-null  int64
 13  runs_batter        278205 non-null  int64
 14  balls_faced        278205 non-null  int64
 15  bowler             278205 non-null  str
 16  valid_ball         278205 non-null  int64
 17  runs_extras        278205 non-null  int64
 18  runs_total         278205 non-null  int64
 19  runs_bowler        278205 non-null  int64
 20  runs_not_boundary  278205 non-null  bool
 21  extra_type         15133 non-null   str
 22  non_striker        278205 non-null  str
 23  non_striker_pos    278205 non-null  int64
 24  wicket_kind        13823 non-null   str
 25  player_out         13823 non-null   str
 26  fielders           10013 non-null   str
 27  runs_target        133903 non-null  float64
 28  review_batter      872 non-null     str
 29  team_reviewed      872 non-null     str
 30  review_decision    872 non-null     str
 31  umpire             872 non-null     str
 32  umpires_call       278205 non-null  bool
 33  player_of_match    278205 non-null  str
 34  match_won_by       278205 non-null  str
 35  win_outcome        273503 non-null  str
 36  toss_winner        278205 non-null  str
 37  toss_decision      278205 non-null  str
 38  venue              278205 non-null  str
 39  city               278205 non-null  str
 40  day                278205 non-null  int64
 41  month              278205 non-null  int64
 42  year               278205 non-null  int64
 43  season             278205 non-null  str
 44  gender             278205 non-null  str
 45  team_type          278205 non-null  str
 46  superover_winner   3896 non-null    str
 47  result_type        4702 non-null    str
 48  method             3890 non-null    str
 49  balls_per_over     278205 non-null  int64
 50  overs              278205 non-null  int64
 51  event_match_no     278205 non-null  str
 52  stage              278205 non-null  str
 53  match_number       278205 non-null  str
 54  team_runs          278205 non-null  int64
 55  team_balls         278205 non-null  int64
 56  team_wicket        278205 non-null  int64
 57  new_batter         13321 non-null   str
 58  batter_runs        278205 non-null  int64
 59  batter_balls       278205 non-null  int64
 60  bowler_wicket      278205 non-null  int64
 61  batting_partners   278205 non-null  str
 62  next_batter        13321 non-null   str
 63  striker_out        278205 non-null  bool
dtypes: bool(3), float64(2), int64(24), str(35)
memory usage: 130.3 MB
None
--------------------------------------------------

In [7]:
print(f"-"*50)
print(ipl_data['overs'].value_counts())
print(f"-"*50)

--------------------------------------------------
overs
20    278205
Name: count, dtype: int64
--------------------------------------------------

In [8]:
print(f"-"*50)
columns_to_drop = ['Unnamed: 0', 'match_type', 'event_name', 'ball', 'runs_not_boundary', 'day', 'month', 'year', 'gender', 'team_type', 'balls_per_over', 'overs', 'over', 'event_match_no', 'match_number', 'batting_partners', 'method', 'new_batter', 'next_batter']
cleaned_ipl_data = ipl_data.drop(columns=columns_to_drop)
print(cleaned_ipl_data.info())
print(f"-"*50)

--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 45 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          278205 non-null  int64
 1   date              278205 non-null  str
 2   innings           278205 non-null  int64
 3   batting_team      278205 non-null  str
 4   bowling_team      278205 non-null  str
 5   ball_no           278205 non-null  float64
 6   batter            278205 non-null  str
 7   bat_pos           278205 non-null  int64
 8   runs_batter       278205 non-null  int64
 9   balls_faced       278205 non-null  int64
 10  bowler            278205 non-null  str
 11  valid_ball        278205 non-null  int64
 12  runs_extras       278205 non-null  int64
 13  runs_total        278205 non-null  int64
 14  runs_bowler       278205 non-null  int64
 15  extra_type        15133 non-null   str
 16  non_striker       278205 non-null  str
 17  non_striker_pos   278205 non-null  int64
 18  wicket_kind       13823 non-null   str
 19  player_out        13823 non-null   str
 20  fielders          10013 non-null   str
 21  runs_target       133903 non-null  float64
 22  review_batter     872 non-null     str
 23  team_reviewed     872 non-null     str
 24  review_decision   872 non-null     str
 25  umpire            872 non-null     str
 26  umpires_call      278205 non-null  bool
 27  player_of_match   278205 non-null  str
 28  match_won_by      278205 non-null  str
 29  win_outcome       273503 non-null  str
 30  toss_winner       278205 non-null  str
 31  toss_decision     278205 non-null  str
 32  venue             278205 non-null  str
 33  city              278205 non-null  str
 34  season            278205 non-null  str
 35  superover_winner  3896 non-null    str
 36  result_type       4702 non-null    str
 37  stage             278205 non-null  str
 38  team_runs         278205 non-null  int64
 39  team_balls        278205 non-null  int64
 40  team_wicket       278205 non-null  int64
 41  batter_runs       278205 non-null  int64
 42  batter_balls      278205 non-null  int64
 43  bowler_wicket     278205 non-null  int64
 44  striker_out       278205 non-null  bool
dtypes: bool(2), float64(2), int64(16), str(25)
memory usage: 91.8 MB
None
--------------------------------------------------

In [9]:
print(f"-"*50)
# -------------- Standardize Team Name --------------
cleaned_ipl_data = cleaned_ipl_data.replace({"Rising Pune Supergiant":"Rising Pune Supergiants"})
print(f"Replaced 'Rising Pune Supergiant' with 'Rising Pune Supergiants'")


# -------------- Standardize Venue Name --------------
cleaned_ipl_data["venue"] = cleaned_ipl_data["venue"].map(lambda x: x.split(",")[0].replace("."," ").replace(" IS Bindra ", " ").strip() if isinstance(x,str) else x)
cleaned_ipl_data["venue"] = cleaned_ipl_data["venue"].replace({
    "Sardar Patel Stadium": "Narendra Modi Stadium",
    "Feroz Shah Kotla": "ARUN JAITLEY STADIUM",
    "Zayed Cricket Stadium": "SHEIKH ZAYED STADIUM"
})
print(f"Cleaned and standardized venue names")


# -------------- Standardize Season Numbers --------------  
cleaned_ipl_data["season"] = cleaned_ipl_data["season"].replace(
    {
        "2007/08":"2008",
        "2009/10":"2010",
        "2020/21":"2020"
    }
)
print(f"Cleaned and standardized season numbers")


# -------------- Standardize Match Stage --------------  
cleaned_ipl_data["stage"] = cleaned_ipl_data["stage"].replace(
    {
        "Unknown": "League"
    }
)
print(f"Cleaned and standardized match stage numbers")


# -------------- Fill Unknown City Name -------------- 
cleaned_ipl_data["city"] = np.where(
    cleaned_ipl_data["city"]=="Unknown",
    cleaned_ipl_data["venue"].str.split(" ").str[0],
    cleaned_ipl_data["city"]
)
cleaned_ipl_data["city"] = cleaned_ipl_data["city"].replace(
    {
        "Bengaluru": "Bangalore",
        "Navi Mumbai": "Mumbai",
        "New Chandigarh": "Chandigarh"
    }
)
print(f"Cleaned and standardized City Names")


print(f"-"*50)

--------------------------------------------------
Replaced 'Rising Pune Supergiant' with 'Rising Pune Supergiants'
Cleaned and standardized venue names
Cleaned and standardized season numbers
Cleaned and standardized match stage numbers
Cleaned and standardized City Names
--------------------------------------------------

In [10]:
print(f"-"*50)
print(cleaned_ipl_data.info())
print(f"-"*50)

--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 45 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          278205 non-null  int64
 1   date              278205 non-null  str
 2   innings           278205 non-null  int64
 3   batting_team      278205 non-null  str
 4   bowling_team      278205 non-null  str
 5   ball_no           278205 non-null  float64
 6   batter            278205 non-null  str
 7   bat_pos           278205 non-null  int64
 8   runs_batter       278205 non-null  int64
 9   balls_faced       278205 non-null  int64
 10  bowler            278205 non-null  str
 11  valid_ball        278205 non-null  int64
 12  runs_extras       278205 non-null  int64
 13  runs_total        278205 non-null  int64
 14  runs_bowler       278205 non-null  int64
 15  extra_type        15133 non-null   str
 16  non_striker       278205 non-null  str
 17  non_striker_pos   278205 non-null  int64
 18  wicket_kind       13823 non-null   str
 19  player_out        13823 non-null   str
 20  fielders          10013 non-null   str
 21  runs_target       133903 non-null  float64
 22  review_batter     872 non-null     str
 23  team_reviewed     872 non-null     str
 24  review_decision   872 non-null     str
 25  umpire            872 non-null     str
 26  umpires_call      278205 non-null  bool
 27  player_of_match   278205 non-null  str
 28  match_won_by      278205 non-null  str
 29  win_outcome       273503 non-null  str
 30  toss_winner       278205 non-null  str
 31  toss_decision     278205 non-null  str
 32  venue             278205 non-null  str
 33  city              278205 non-null  str
 34  season            278205 non-null  str
 35  superover_winner  3896 non-null    str
 36  result_type       4702 non-null    str
 37  stage             278205 non-null  str
 38  team_runs         278205 non-null  int64
 39  team_balls        278205 non-null  int64
 40  team_wicket       278205 non-null  int64
 41  batter_runs       278205 non-null  int64
 42  batter_balls      278205 non-null  int64
 43  bowler_wicket     278205 non-null  int64
 44  striker_out       278205 non-null  bool
dtypes: bool(2), float64(2), int64(16), str(25)
memory usage: 91.8 MB
None
--------------------------------------------------

In [11]:
print(f"-"*50)

# =================================================
#               Categorical Columns
# =================================================
categorical_columns = ["batting_team", "bowling_team", "batter", "bowler","extra_type", "non_striker", "wicket_kind", "player_out", "fielders", "review_batter", "umpire", "player_of_match", "match_won_by", "win_outcome", "toss_winner", "toss_decision", "venue", "city", "superover_winner", "result_type", "stage", "team_reviewed", "review_decision"]
for col in categorical_columns:
    try:
        cleaned_ipl_data[col] = cleaned_ipl_data[col].astype(str)
        cleaned_ipl_data[col] = cleaned_ipl_data[col].map(lambda x: x.strip().upper() if isinstance(x,str) else x)
    except Exception as e:
        raise Exception(f"Failed to convert {col} column to string.")
print(f"Identified and type-casted {len(categorical_columns)} categorical columns")


# =================================================
#               Numerical Columns
# =================================================
numerical_columns = ["match_id", "innings","bat_pos", "runs_batter", "balls_faced", "runs_extras", "runs_total", "runs_bowler", "non_striker_pos", "runs_target", "season", "team_runs", "team_balls", "team_wicket", "batter_runs", "batter_balls", "bowler_wicket", "ball_no"]
for col in numerical_columns:
    try:
        cleaned_ipl_data[col] = cleaned_ipl_data[col].astype(float)
    except Exception as e:
        raise Exception(f"Failed to convert {col} column to float.")
print(f"Identified and type-casted {len(numerical_columns)} float columns")


# =================================================
#               Boolean Columns
# =================================================
boolean_columns = ["valid_ball", "umpires_call", "striker_out"]
for col in boolean_columns:
    try:
        cleaned_ipl_data[col] = cleaned_ipl_data[col].astype(bool)
    except Exception as e:
        raise Exception(f"Failed to convert {col} column to boolean.")
print(f"Identified and type-casted {len(boolean_columns)} boolean columns")


# =================================================
#               Date Columns
# =================================================
date_columns = ["date"]
for col in date_columns:
    try:
        cleaned_ipl_data[col] = pd.to_datetime(cleaned_ipl_data[col]).dt.date
    except Exception as e:
        raise Exception(f"Failed to convert {col} column to date.")
print(f"Identified and type-casted {len(date_columns)} date columns")


# =================================================
#               Total (All) Columns
# =================================================
total_columns = len(categorical_columns) + len(numerical_columns) + len(boolean_columns) + len(date_columns)
print(f"Total {total_columns} columns identified and type-casted correctly!")

print(f"-"*50)

--------------------------------------------------
Identified and type-casted 23 categorical columns
Identified and type-casted 18 float columns
Identified and type-casted 3 boolean columns
Identified and type-casted 1 date columns
Total 45 columns identified and type-casted correctly!
--------------------------------------------------

In [12]:
cleaned_ipl_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 45 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          278205 non-null  float64
 1   date              278205 non-null  object
 2   innings           278205 non-null  float64
 3   batting_team      278205 non-null  str
 4   bowling_team      278205 non-null  str
 5   ball_no           278205 non-null  float64
 6   batter            278205 non-null  str
 7   bat_pos           278205 non-null  float64
 8   runs_batter       278205 non-null  float64
 9   balls_faced       278205 non-null  float64
 10  bowler            278205 non-null  str
 11  valid_ball        278205 non-null  bool
 12  runs_extras       278205 non-null  float64
 13  runs_total        278205 non-null  float64
 14  runs_bowler       278205 non-null  float64
 15  extra_type        15133 non-null   str
 16  non_striker       278205 non-null  str
 17  non_striker_pos   278205 non-null  float64
 18  wicket_kind       13823 non-null   str
 19  player_out        13823 non-null   str
 20  fielders          10013 non-null   str
 21  runs_target       133903 non-null  float64
 22  review_batter     872 non-null     str
 23  team_reviewed     872 non-null     str
 24  review_decision   872 non-null     str
 25  umpire            872 non-null     str
 26  umpires_call      278205 non-null  bool
 27  player_of_match   278205 non-null  str
 28  match_won_by      278205 non-null  str
 29  win_outcome       273503 non-null  str
 30  toss_winner       278205 non-null  str
 31  toss_decision     278205 non-null  str
 32  venue             278205 non-null  str
 33  city              278205 non-null  str
 34  season            278205 non-null  float64
 35  superover_winner  3896 non-null    str
 36  result_type       4702 non-null    str
 37  stage             278205 non-null  str
 38  team_runs         278205 non-null  float64
 39  team_balls        278205 non-null  float64
 40  team_wicket       278205 non-null  float64
 41  batter_runs       278205 non-null  float64
 42  batter_balls      278205 non-null  float64
 43  bowler_wicket     278205 non-null  float64
 44  striker_out       278205 non-null  bool
dtypes: bool(3), float64(18), object(1), str(23)
memory usage: 89.9+ MB

In [13]:
cleaned_ipl_data.to_csv("./data/Cleaned-IPL-Data.csv", index=False)

### Umpire Dimension Table

In [14]:
umpire_dim_table = cleaned_ipl_data[["umpire"]].drop_duplicates().dropna().reset_index(drop=True)
umpire_dim_table["umpire_id"] = range(1, len(umpire_dim_table) + 1)
umpire_dim_table = umpire_dim_table[["umpire_id", "umpire"]]
print(f"Built umpire Dimension table with size - {umpire_dim_table.shape}")
umpire_dim_table.sort_values(by="umpire")

Built umpire Dimension table with size - (47, 2)

    umpire_id                 umpire
39         40              A BENGERI
3           4             A DESHMUKH
11         12         A NAND KISHORE
35         36                A TOTRE
38         39   ABHIJIT BHATTACHARYA
37         38               AG WHARF
5           6           AK CHAUDHARY
46         47     ANISH SAHASRABUDHE
40         41           AT HOLDSTOCK
17         18            AY DANDEKAR
16         17           BNJ OXENFORD
2           3          C SHAMSHUDDIN
0           1            CB GAFFANEY
31         32  CHIRRA RAVIKANTHREDDY
6           7              CK NANDAN
33         34       GR SADASHIV IYER
27         28             HAS KHALID
15         16        HDPK DHARMASENA
19         20               IJ GOULD
24         25          J MADANAGOPAL
44         45               K KELKAR
22         23           K SRINIVASAN
41         42         K SWAROOPANAND
45         46              KM GANDHI
10         11  KN ANANTHAPADMANABHAN
14         15              M ERASMUS
43         44           M KRISHNADAS
28         29               MA GOUGH
36         37   MV SAIDHARSHAN KUMAR
29         30               N PANDIT
32         33          NA PATWARDHAN
25         26          NAVDEEP SINGH
9          10            NITIN MENON
7           8               NJ LLONG
42         43                P JOSHI
23         24              PG PATHAK
20         21             PR REIFFEL
30         31               R PANDIT
1           2              RJ TUCKER
21         22         RK ILLINGWORTH
8           9                 S RAVI
26         27           TAPAN SHARMA
18         19              UV GANDHE
4           5            VA KULKARNI
34         35           VINOD SESHAN
12         13              VK SHARMA
13         14               YC BARDE

In [16]:
umpire_dim_table.to_csv("database-tables/umpire-dim-table.csv",index=False)

### Player Dimension Table

In [17]:
player_name_cols = ["batter", "bowler", "non_striker", "fielders", "player_out", "player_of_match", "review_batter"]

all_player_names = []

for col in player_name_cols:
    unique_player_names = cleaned_ipl_data[col].map(lambda x: x.strip().upper() if isinstance(x,str) else x).dropna().values.tolist()
    # print(unique_player_names)
    cleaned_unique_player_names = [str(val).split(",") for val in unique_player_names]
    flat_unique_player_names = [item for sublist in cleaned_unique_player_names for item in sublist]
    flat_unique_player_names = list(set(flat_unique_player_names))
    print(f"Found {len(flat_unique_player_names)} unique players from {col} column.")

    all_player_names.extend(flat_unique_player_names)

all_player_names = list(set(all_player_names))
print(f"Found {len(all_player_names)} unique players overall!")

Found 703 unique players from batter column.
Found 550 unique players from bowler column.
Found 692 unique players from non_striker column.
Found 642 unique players from fielders column.
Found 655 unique players from player_out column.
Found 309 unique players from player_of_match column.
Found 202 unique players from review_batter column.
Found 779 unique players overall!

In [18]:
player_dim_table = pd.DataFrame(columns=["player_id", "player_name"])
player_dim_table["player_name"] = all_player_names
player_dim_table["player_id"] = range(1, len(player_dim_table) + 1)

print(f"Built Player Dimension table with size - {player_dim_table.shape}")
player_dim_table.head()

Built Player Dimension table with size - (779, 2)

   player_id   player_name
0          1    GD MCGRATH
1          2      B GEEVES
2          3  BB SAMANTRAY
3          4   MP BREETZKE
4          5     J OVERTON

In [20]:
player_dim_table.to_csv("database-tables/player-dim-table.csv",index=False)

### Team Dimension Table

In [21]:
team_name_cols = ["batting_team", "bowling_team", "match_won_by", "toss_winner", "superover_winner", "team_reviewed"]

all_team_names = []

for col in team_name_cols:
    unique_team_names = cleaned_ipl_data[col].dropna().map(lambda x: x.strip().upper() if isinstance(x,str) else x).dropna().values.tolist()
    unique_team_names = list(set(unique_team_names))
    print(f"Found {len(unique_team_names)} unique teams from {col} column.")

    all_team_names.extend(unique_team_names)

all_team_names = list(set(all_team_names))
all_team_names.remove("UNKNOWN")
print(f"Found {len(all_team_names)} unique teams overall!")

Found 18 unique teams from batting_team column.
Found 18 unique teams from bowling_team column.
Found 19 unique teams from match_won_by column.
Found 18 unique teams from toss_winner column.
Found 7 unique teams from superover_winner column.
Found 13 unique teams from team_reviewed column.
Found 18 unique teams overall!

In [22]:
team_dim_table = pd.DataFrame(columns=["team_id", "team_name"])
team_dim_table["team_name"] = all_team_names
team_dim_table["team_id"] = range(1, len(team_dim_table) + 1)

print(f"Built team Dimension table with size - {team_dim_table.shape}")
team_dim_table

Built team Dimension table with size - (18, 2)

    team_id                    team_name
0         1      RISING PUNE SUPERGIANTS
1         2               GUJARAT TITANS
2         3             RAJASTHAN ROYALS
3         4         LUCKNOW SUPER GIANTS
4         5                PUNE WARRIORS
5         6               DELHI CAPITALS
6         7          CHENNAI SUPER KINGS
7         8        KOLKATA KNIGHT RIDERS
8         9  ROYAL CHALLENGERS BENGALURU
9        10             DELHI DAREDEVILS
10       11  ROYAL CHALLENGERS BANGALORE
11       12              DECCAN CHARGERS
12       13                GUJARAT LIONS
13       14               MUMBAI INDIANS
14       15              KINGS XI PUNJAB
15       16                 PUNJAB KINGS
16       17          SUNRISERS HYDERABAD
17       18         KOCHI TUSKERS KERALA

In [23]:
team_dim_table.to_csv("database-tables/team-dim-table.csv",index=False)

### Venue Dimension Table

In [24]:
city_column = "city"
all_city_names = cleaned_ipl_data[city_column].unique().tolist()
print(all_city_names)

['BANGALORE', 'CHANDIGARH', 'DELHI', 'MUMBAI', 'KOLKATA', 'JAIPUR', 'HYDERABAD', 'CHENNAI', 'CAPE TOWN', 'PORT ELIZABETH', 'DURBAN', 'CENTURION', 'EAST LONDON', 'JOHANNESBURG', 'KIMBERLEY', 'BLOEMFONTEIN', 'AHMEDABAD', 'CUTTACK', 'NAGPUR', 'DHARAMSALA', 'KOCHI', 'INDORE', 'VISAKHAPATNAM', 'PUNE', 'RAIPUR', 'RANCHI', 'ABU DHABI', 'SHARJAH', 'DUBAI', 'RAJKOT', 'KANPUR', 'LUCKNOW', 'GUWAHATI', 'MOHALI']

In [25]:
stadium_column = "venue"
all_venue_names = sorted(cleaned_ipl_data[stadium_column].unique())
print(all_venue_names)

['ARUN JAITLEY STADIUM', 'BARABATI STADIUM', 'BARSAPARA CRICKET STADIUM', 'BHARAT RATNA SHRI ATAL BIHARI VAJPAYEE EKANA CRICKET STADIUM', 'BRABOURNE STADIUM', 'BUFFALO PARK', 'DE BEERS DIAMOND OVAL', 'DR  Y S  RAJASEKHARA REDDY ACA-VDCA CRICKET STADIUM', 'DR DY PATIL SPORTS ACADEMY', 'DUBAI INTERNATIONAL CRICKET STADIUM', 'EDEN GARDENS', 'GREEN PARK', 'HIMACHAL PRADESH CRICKET ASSOCIATION STADIUM', 'HOLKAR CRICKET STADIUM', 'JSCA INTERNATIONAL STADIUM COMPLEX', 'KINGSMEAD', 'M CHINNASWAMY STADIUM', 'MA CHIDAMBARAM STADIUM', 'MAHARAJA YADAVINDRA SINGH INTERNATIONAL CRICKET STADIUM', 'MAHARASHTRA CRICKET ASSOCIATION STADIUM', 'NARENDRA MODI STADIUM', 'NEHRU STADIUM', 'NEW WANDERERS STADIUM', 'NEWLANDS', 'OUTSURANCE OVAL', 'PUNJAB CRICKET ASSOCIATION STADIUM', 'RAJIV GANDHI INTERNATIONAL STADIUM', 'SAURASHTRA CRICKET ASSOCIATION STADIUM', 'SAWAI MANSINGH STADIUM', 'SHAHEED VEER NARAYAN SINGH INTERNATIONAL STADIUM', 'SHARJAH CRICKET STADIUM', 'SHEIKH ZAYED STADIUM', "ST GEORGE'S PARK", 'SUBRATA ROY SAHARA STADIUM', 'SUPERSPORT PARK', 'VIDARBHA CRICKET ASSOCIATION STADIUM', 'WANKHEDE STADIUM']

In [26]:
venue_dim_table = cleaned_ipl_data[[city_column, stadium_column]].drop_duplicates().sort_values(city_column).reset_index(drop=True)
venue_dim_table["venue_id"] = range(1, len(venue_dim_table) + 1)

venue_dim_table = venue_dim_table[["venue_id", stadium_column, city_column]]
print(f"Built venue Dimension table with size - {venue_dim_table.shape}")
venue_dim_table

Built venue Dimension table with size - (38, 3)

,venue_id,venue,city
0,1,SHEIKH ZAYED STADIUM,ABU DHABI
1,2,NARENDRA MODI STADIUM,AHMEDABAD
2,3,M CHINNASWAMY STADIUM,BANGALORE
3,4,OUTSURANCE OVAL,BLOEMFONTEIN
4,5,NEWLANDS,CAPE TOWN
5,6,SUPERSPORT PARK,CENTURION
6,7,MAHARAJA YADAVINDRA SINGH INTERNATIONAL CRICKE...,CHANDIGARH
7,8,PUNJAB CRICKET ASSOCIATION STADIUM,CHANDIGARH
8,9,MA CHIDAMBARAM STADIUM,CHENNAI
9,10,BARABATI STADIUM,CUTTACK
10,11,ARUN JAITLEY STADIUM,DELHI
11,12,HIMACHAL PRADESH CRICKET ASSOCIATION STADIUM,DHARAMSALA
12,13,DUBAI INTERNATIONAL CRICKET STADIUM,DUBAI
13,14,KINGSMEAD,DURBAN
14,15,BUFFALO PARK,EAST LONDON
15,16,BARSAPARA CRICKET STADIUM,GUWAHATI
16,17,RAJIV GANDHI INTERNATIONAL STADIUM,HYDERABAD
17,18,HOLKAR CRICKET STADIUM,INDORE
18,19,SAWAI MANSINGH STADIUM,JAIPUR
19,20,NEW WANDERERS STADIUM,JOHANNESBURG
20,21,GREEN PARK,KANPUR
21,22,DE BEERS DIAMOND OVAL,KIMBERLEY
22,23,NEHRU STADIUM,KOCHI
23,24,EDEN GARDENS,KOLKATA
24,25,BHARAT RATNA SHRI ATAL BIHARI VAJPAYEE EKANA C...,LUCKNOW
25,26,MAHARAJA YADAVINDRA SINGH INTERNATIONAL CRICKE...,MOHALI
26,27,WANKHEDE STADIUM,MUMBAI
27,28,BRABOURNE STADIUM,MUMBAI
28,29,DR DY PATIL SPORTS ACADEMY,MUMBAI
29,30,VIDARBHA CRICKET ASSOCIATION STADIUM,NAGPUR
30,31,ST GEORGE'S PARK,PORT ELIZABETH
31,32,SUBRATA ROY SAHARA STADIUM,PUNE
32,33,MAHARASHTRA CRICKET ASSOCIATION STADIUM,PUNE
33,34,SHAHEED VEER NARAYAN SINGH INTERNATIONAL STADIUM,RAIPUR
34,35,SAURASHTRA CRICKET ASSOCIATION STADIUM,RAJKOT
35,36,JSCA INTERNATIONAL STADIUM COMPLEX,RANCHI
36,37,SHARJAH CRICKET STADIUM,SHARJAH
37,38,DR Y S RAJASEKHARA REDDY ACA-VDCA CRICKET ST...,VISAKHAPATNAM

In [27]:
venue_dim_table.to_csv("database-tables/venue-dim-table.csv",index=False)

### Season Dimension Table

In [28]:
season_dim_table = cleaned_ipl_data[["season"]].drop_duplicates().reset_index(drop=True)
season_dim_table["season_id"] = range(1, len(season_dim_table) + 1)
season_dim_table = season_dim_table[["season_id", "season"]]
print(f"Built season Dimension table with size - {season_dim_table.shape}")
season_dim_table

Built season Dimension table with size - (18, 2)

    season_id  season
0           1  2008.0
1           2  2009.0
2           3  2010.0
3           4  2011.0
4           5  2012.0
5           6  2013.0
6           7  2014.0
7           8  2015.0
8           9  2016.0
9          10  2017.0
10         11  2018.0
11         12  2019.0
12         13  2020.0
13         14  2021.0
14         15  2022.0
15         16  2023.0
16         17  2024.0
17         18  2025.0

In [29]:
season_dim_table.to_csv("database-tables/season-dim-table.csv",index=False)

### Match Dimension Table

In [30]:
match_cols = ["match_id", "date", "toss_decision", "win_outcome", "result_type", "stage", "runs_target", "season", "toss_winner", "match_won_by", "player_of_match", "superover_winner", "venue", "city"]

match_dim_table = cleaned_ipl_data[match_cols].drop_duplicates().reset_index(drop=True)

team_map = team_dim_table.set_index("team_name")["team_id"]
season_map = season_dim_table.set_index("season")["season_id"]
pom_map = player_dim_table.set_index("player_name")["player_id"]
venue_map = venue_dim_table.set_index(["venue", "city"])["venue_id"]

match_dim_table["season_id"] = (match_dim_table["season"].map(season_map))
match_dim_table["venue_id"] = (match_dim_table[["venue","city"]].apply(tuple, axis=1).map(venue_map))
match_dim_table["toss_winner_id"] = (match_dim_table["toss_winner"].map(team_map))
match_dim_table["match_winner_id"] = (match_dim_table["match_won_by"].map(team_map))
match_dim_table["player_of_match_id"] = (match_dim_table["player_of_match"].map(pom_map))
match_dim_table["superover_winner_id"] = (match_dim_table["superover_winner"].map(team_map))

match_dim_table = match_dim_table.drop(columns=match_cols[7:])

match_dim_table.head()

,match_id,date,toss_decision,win_outcome,result_type,stage,runs_target,season_id,venue_id,toss_winner_id,match_winner_id,player_of_match_id,superover_winner_id
0,335982.0,2008-04-18,FIELD,140 RUNS,NaN,LEAGUE,NaN,1,3,11,8.0,718,NaN
1,335982.0,2008-04-18,FIELD,140 RUNS,NaN,LEAGUE,223.0,1,3,11,8.0,718,NaN
2,335983.0,2008-04-19,BAT,33 RUNS,NaN,LEAGUE,NaN,1,8,7,7.0,540,NaN
3,335983.0,2008-04-19,BAT,33 RUNS,NaN,LEAGUE,241.0,1,8,7,7.0,540,NaN
4,335984.0,2008-04-19,BAT,9 WICKETS,NaN,LEAGUE,NaN,1,11,3,10.0,464,NaN

In [31]:
single_entries = match_dim_table["match_id"].value_counts()[match_dim_table["match_id"].value_counts()==1].keys().tolist()
match_dim_table[match_dim_table['match_id'].isin(single_entries)]

,match_id,date,toss_decision,win_outcome,result_type,stage,runs_target,season_id,venue_id,toss_winner_id,match_winner_id,player_of_match_id,superover_winner_id
482,501265.0,2011-05-21,BAT,NaN,NO RESULT,LEAGUE,NaN,4,11,10,NaN,572,NaN
969,829763.0,2015-04-29,FIELD,NaN,NO RESULT,LEAGUE,NaN,8,3,3,NaN,572,NaN
1986,1359519.0,2023-05-03,FIELD,NaN,NO RESULT,LEAGUE,NaN,16,25,7,NaN,572,NaN
2295,1473492.0,2025-05-05,FIELD,NaN,NO RESULT,LEAGUE,NaN,18,17,17,NaN,572,NaN
2300,1473495.0,2025-05-08,BAT,NaN,NO RESULT,LEAGUE,NaN,18,12,16,NaN,572,NaN

In [32]:
match_dim_table.to_csv("database-tables/match-dim-table.csv",index=False)

### Delivery Fact Table

In [33]:
delivery_cols = ["match_id", "innings", "ball_no", "runs_batter", "runs_extras", "runs_total", "runs_bowler", "valid_ball", "extra_type", "wicket_kind", "review_decision", "umpires_call", "team_runs", "team_balls", "team_wicket", "batter_runs", "batter_balls", "bowler_wicket", "striker_out", "batting_team", "bowling_team", "batter", "non_striker", "bowler", "player_out", "fielders", "review_batter", "team_reviewed", "umpire"]

delivery_fact_table = cleaned_ipl_data[delivery_cols].drop_duplicates().reset_index(drop=True)

team_map = team_dim_table.set_index("team_name")["team_id"]
player_map = player_dim_table.set_index("player_name")["player_id"]
umpire_map = umpire_dim_table.set_index("umpire")["umpire_id"]


delivery_fact_table["batting_team_id"] = (delivery_fact_table["batting_team"].map(team_map))
delivery_fact_table["bowling_team_id"] = (delivery_fact_table["bowling_team"].map(team_map))
delivery_fact_table["batter_id"] = (delivery_fact_table["batter"].map(player_map))
delivery_fact_table["non_striker_id"] = (delivery_fact_table["non_striker"].map(player_map))
delivery_fact_table["bowler_id"] = (delivery_fact_table["bowler"].map(player_map))
delivery_fact_table["player_out_id"] = (delivery_fact_table["player_out"].map(player_map))
delivery_fact_table["fielder_id"] = (delivery_fact_table["fielders"].map(player_map))
delivery_fact_table["review_batter_id"] = (delivery_fact_table["review_batter"].map(player_map))
delivery_fact_table["team_reviewed_id"] = (delivery_fact_table["team_reviewed"].map(team_map))
delivery_fact_table["umpire_id"] = (delivery_fact_table["umpire"].map(umpire_map))


delivery_fact_table = delivery_fact_table.drop(columns=delivery_cols[19:])
delivery_fact_table

,match_id,innings,ball_no,runs_batter,runs_extras,runs_total,runs_bowler,valid_ball,extra_type,wicket_kind,...,batting_team_id,bowling_team_id,batter_id,non_striker_id,bowler_id,player_out_id,fielder_id,review_batter_id,team_reviewed_id,umpire_id
0,335982.0,1.0,0.1,0.0,1.0,1.0,0.0,True,LEGBYES,NaN,...,8,11,447,718,529,NaN,NaN,NaN,NaN,NaN
1,335982.0,1.0,0.2,0.0,0.0,0.0,0.0,True,NaN,NaN,...,8,11,718,447,529,NaN,NaN,NaN,NaN,NaN
2,335982.0,1.0,0.3,0.0,1.0,1.0,1.0,False,WIDES,NaN,...,8,11,718,447,529,NaN,NaN,NaN,NaN,NaN
3,335982.0,1.0,0.3,0.0,0.0,0.0,0.0,True,NaN,NaN,...,8,11,718,447,529,NaN,NaN,NaN,NaN,NaN
4,335982.0,1.0,0.4,0.0,0.0,0.0,0.0,True,NaN,NaN,...,8,11,718,447,529,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278200,1473511.0,2.0,19.2,0.0,0.0,0.0,0.0,True,NaN,NaN,...,16,9,571,515,466,NaN,NaN,NaN,NaN,NaN
278201,1473511.0,2.0,19.3,6.0,0.0,6.0,6.0,True,NaN,NaN,...,16,9,571,515,466,NaN,NaN,NaN,NaN,NaN
278202,1473511.0,2.0,19.4,4.0,0.0,4.0,4.0,True,NaN,NaN,...,16,9,571,515,466,NaN,NaN,NaN,NaN,NaN
278203,1473511.0,2.0,19.5,6.0,0.0,6.0,6.0,True,NaN,NaN,...,16,9,571,515,466,NaN,NaN,NaN,NaN,NaN
278204,1473511.0,2.0,19.6,6.0,0.0,6.0,6.0,True,NaN,NaN,...,16,9,571,515,466,NaN,NaN,NaN,NaN,NaN

In [34]:
delivery_fact_table.to_csv("database-tables/delivery-fact-table.csv",index=False)

### Enriched Delivery Fact Table

In [35]:
enriched_delivery_fact_table = delivery_fact_table.copy()

In [36]:
def find_phase(row):
    if row["innings"]>2:
        return "Super Over"
    elif 1<=row["over_number"]<=6:
        return "Powerplay Over"
    elif 6<=row["over_number"]<=15:
        return "Middle Over"
    elif 16<=row["over_number"]<=20:
        return "Death Over"
    else:
        return None

# -----------------is_dot_ball-----------------
enriched_delivery_fact_table["is_dot_ball"] = np.where(
    enriched_delivery_fact_table["runs_total"]==0,
    True,
    False
)

# -----------------is_four-----------------
enriched_delivery_fact_table["is_four"] = np.where(
    enriched_delivery_fact_table["runs_batter"]==4,
    True,
    False
)

# -----------------is_six-----------------
enriched_delivery_fact_table["is_six"] = np.where(
    enriched_delivery_fact_table["runs_batter"]==6,
    True,
    False
)

# -----------------is_boundary-----------------
enriched_delivery_fact_table["is_boundary"] = np.where(
    (enriched_delivery_fact_table["is_four"] | enriched_delivery_fact_table["is_six"]),
    True,
    False
)

# -----------------is_wicket-----------------
enriched_delivery_fact_table["is_wicket"] = np.where(
    enriched_delivery_fact_table["wicket_kind"].notna(),
    True,
    False
)

# -----------------is_bowler_wicket-----------------
enriched_delivery_fact_table["bowler_wicket"] = enriched_delivery_fact_table["bowler_wicket"].replace({0:False, 1:True})
enriched_delivery_fact_table = enriched_delivery_fact_table.rename(columns={
    "bowler_wicket": "is_bowler_wicket"
})

# -----------------over_number-----------------
enriched_delivery_fact_table["over_number"] = np.floor(enriched_delivery_fact_table["ball_no"])+1

# -----------------over phase-----------------
enriched_delivery_fact_table["phase"] = enriched_delivery_fact_table.apply(find_phase, axis=1)

In [37]:
enriched_delivery_fact_table.head()

,match_id,innings,ball_no,runs_batter,runs_extras,runs_total,runs_bowler,valid_ball,extra_type,wicket_kind,...,review_batter_id,team_reviewed_id,umpire_id,is_dot_ball,is_four,is_six,is_boundary,is_wicket,over_number,phase
0,335982.0,1.0,0.1,0.0,1.0,1.0,0.0,True,LEGBYES,NaN,...,NaN,NaN,NaN,False,False,False,False,False,1.0,Powerplay Over
1,335982.0,1.0,0.2,0.0,0.0,0.0,0.0,True,NaN,NaN,...,NaN,NaN,NaN,True,False,False,False,False,1.0,Powerplay Over
2,335982.0,1.0,0.3,0.0,1.0,1.0,1.0,False,WIDES,NaN,...,NaN,NaN,NaN,False,False,False,False,False,1.0,Powerplay Over
3,335982.0,1.0,0.3,0.0,0.0,0.0,0.0,True,NaN,NaN,...,NaN,NaN,NaN,True,False,False,False,False,1.0,Powerplay Over
4,335982.0,1.0,0.4,0.0,0.0,0.0,0.0,True,NaN,NaN,...,NaN,NaN,NaN,True,False,False,False,False,1.0,Powerplay Over

In [38]:
enriched_delivery_fact_table.to_csv("database-tables/enriched-delivery-fact-table.csv",index=False)

### Agg Player Batting Table

In [40]:
player_id_col = []
season_id_col = []
matches_col = []
innings_col = []
runs_col = []
balls_col = []
average_col = []
strike_rate_col = []
fours_col = []
sixes_col = []
fifties_col = []
hundreds_col = []
dot_ball_pct_col = []
boundary_pct_col = []
highest_score_col = []


season_map = season_dim_table.set_index("season")["season_id"]
player_map = player_dim_table.set_index("player_name")["player_id"]

for key,values in cleaned_ipl_data.groupby(by=["batter", "season"]):

    # -------------------------------------------------------------
    #                       Calculate Values
    # -------------------------------------------------------------
    runs = values["runs_batter"].sum()
    matches = values["match_id"].nunique()
    balls = values["balls_faced"].sum()

    try:
        fours = values["runs_batter"].value_counts()[4]
    except:
        fours = 0
    
    try:
        sixes = values["runs_batter"].value_counts()[6]
    except:
        sixes=0
    
    fifties = 0
    hundereds = 0
    highest_score = -1
    for _,v in values.groupby(["match_id", "innings"]):
        runs_total = v["runs_batter"].sum()
        if runs_total>=100:
            hundereds += 1
        elif runs_total>=50:
            fifties += 1
        if runs_total>highest_score:
            highest_score = runs_total
    try:
        dot_balls_pct = round(values["runs_total"].value_counts()[0]/balls * 100, 2)
    except KeyError:
        dot_balls_pct = 0
    
    boundary_pct = round((fours+sixes)/balls*100, 2)

    # -------------------------------------------------------------
    #                       Append Values
    # -------------------------------------------------------------
    player_id_col.append(player_map[key[0]])
    season_id_col.append(season_map[key[1]])
    matches_col.append(matches)
    innings_col.append(values[["match_id","innings"]].drop_duplicates().shape[0])
    runs_col.append(runs)
    balls_col.append(balls)
    average_col.append(round(runs/matches, 2))
    strike_rate_col.append(round(runs/balls*100, 2))
    fours_col.append(fours)
    sixes_col.append(sixes)
    fifties_col.append(fifties)
    hundreds_col.append(hundereds)
    dot_ball_pct_col.append(dot_balls_pct)
    boundary_pct_col.append(boundary_pct)
    highest_score_col.append(highest_score)

In [41]:
# -------------------------------------------------------------
#                       Build Dataframe
# -------------------------------------------------------------

agg_player_batting_table = pd.DataFrame()
agg_player_batting_table["player_id"] = player_id_col
agg_player_batting_table["season_id"] = season_id_col
agg_player_batting_table["matches"] = matches_col
agg_player_batting_table["innings"] = innings_col
agg_player_batting_table["runs"] = runs_col
agg_player_batting_table["balls"] = balls_col
agg_player_batting_table["average"] = average_col
agg_player_batting_table["strike_rate"] = strike_rate_col
agg_player_batting_table["fours"] = fours_col
agg_player_batting_table["sixes"] = sixes_col
agg_player_batting_table["fifties"] = fifties_col
agg_player_batting_table["hundreds"] = hundreds_col
agg_player_batting_table["dot_ball_pct"] = dot_ball_pct_col
agg_player_batting_table["boundary_pct"] = boundary_pct_col
agg_player_batting_table["highest_score"] = highest_score_col

agg_player_batting_table.head()

,player_id,season_id,matches,innings,runs,balls,average,strike_rate,fours,sixes,fifties,hundreds,dot_ball_pct,boundary_pct,highest_score
0,455,5,5,5,35.0,29.0,7.00,120.69,3,1,0,0,37.93,13.79,10.0
1,455,6,10,10,125.0,89.0,12.50,140.45,8,5,0,0,26.97,14.61,36.0
2,455,8,5,5,73.0,46.0,14.60,158.70,3,5,0,0,26.09,17.39,22.0
3,455,9,3,3,47.0,29.0,15.67,162.07,2,4,0,0,31.03,20.69,32.0
4,144,15,11,11,161.0,130.0,14.64,123.85,11,7,1,0,36.15,13.85,54.0

In [43]:
agg_player_batting_table.to_csv("database-tables/agg-player-batting-table.csv",index=False)

### Agg Player Bowling Table

In [44]:
player_id_col = []
season_id_col = []
matches_col = []
innings_col = []
balls_bowled_col = []
overs_col = []
runs_conceded_col = []
wickets_col = []
economy_col = []
bowling_avg_col = []
bowling_sr_col = []
dot_balls_col = []
dot_balls_pct_col = []
fours_conceded_col = []
sixes_conceded_col = []
best_bowling_figs_col = []

season_map = season_dim_table.set_index("season")["season_id"]
player_map = player_dim_table.set_index("player_name")["player_id"]

for key,values in cleaned_ipl_data.groupby(by=["bowler", "season"]):

    # -------------------------------------------------------------
    #                       Calculate Values
    # -------------------------------------------------------------
    runs = values["runs_batter"].sum()
    matches = values["match_id"].nunique()
    balls = values["valid_ball"].value_counts()[True]
    values["over"] = np.ceil(values["ball_no"])
    overs = values[["match_id","over"]].drop_duplicates().shape[0]
    runs = values["runs_bowler"].sum()
    wickets = values["bowler_wicket"].sum()
    economy = round(runs/overs, 2)
    bowling_avg = round(runs/wickets, 2) if wickets!=0 else 0
    bowling_sr = round(balls/wickets, 2) if wickets!=0 else 0
    try:
        dot_balls = values["runs_total"].value_counts()[0]
        dot_balls_pct = round(dot_balls/balls * 100, 2)
    except KeyError:
        dot_balls = 0
        dot_balls_pct = 0

    try:
        fours = values["runs_batter"].value_counts()[4]
    except:
        fours = 0
    
    try:
        sixes = values["runs_batter"].value_counts()[6]
    except:
        sixes = 0
    
    most_wicks = -1
    most_runs = -1
    for k,v in values.groupby(["match_id"]):

        if (v["bowler_wicket"].sum()>most_wicks) or (v["bowler_wicket"].sum()==most_wicks and v["runs_bowler"].sum()<most_runs):
            most_wicks = int(v["bowler_wicket"].sum())
            most_runs = int(v["runs_bowler"].sum())

    bbf = f"{most_wicks}/{most_runs}"

    # -------------------------------------------------------------
    #                       Append Values
    # -------------------------------------------------------------
    player_id_col.append(player_map[key[0]])
    season_id_col.append(season_map[key[1]])
    matches_col.append(matches)
    innings_col.append(values[["match_id","innings"]].drop_duplicates().shape[0])
    balls_bowled_col.append(balls)
    overs_col.append(overs)
    runs_conceded_col.append(runs)
    wickets_col.append(wickets)
    economy_col.append(economy)
    bowling_avg_col.append(bowling_avg)
    bowling_sr_col.append(bowling_sr)
    dot_balls_col.append(dot_balls)
    dot_balls_pct_col.append(dot_balls_pct)
    fours_conceded_col.append(fours)
    sixes_conceded_col.append(sixes)
    best_bowling_figs_col.append(bbf)

    if key[0]=="B KUMAR":
        print(key[0], key[1], matches, balls, overs, runs, wickets, economy, bowling_avg, bowling_sr, dot_balls, dot_balls_pct, fours, sixes, bbf)

B KUMAR 2011.0 4 66 11 67.0 3.0 6.09 22.33 22.0 28 42.42 7 1 2/14
B KUMAR 2012.0 11 234 39 281.0 8.0 7.21 35.12 29.25 86 36.75 22 10 2/9
B KUMAR 2013.0 16 342 57 371.0 13.0 6.51 28.54 26.31 167 48.83 43 5 3/18
B KUMAR 2014.0 14 319 55 354.0 20.0 6.44 17.7 15.95 152 47.65 42 8 4/14
B KUMAR 2015.0 14 310 52 407.0 18.0 7.83 22.61 17.22 126 40.65 41 14 3/26
B KUMAR 2016.0 17 396 66 490.0 23.0 7.42 21.3 17.22 156 39.39 54 8 4/29
B KUMAR 2017.0 14 314 53 369.0 26.0 6.96 14.19 12.08 117 37.26 35 9 5/19
B KUMAR 2018.0 12 277 47 354.0 9.0 7.53 39.33 30.78 121 43.68 30 16 3/26
B KUMAR 2019.0 15 354 59 461.0 13.0 7.81 35.46 27.23 163 46.05 49 16 2/24
B KUMAR 2020.0 4 85 15 99.0 3.0 6.6 33.0 28.33 39 45.88 13 1 2/25
B KUMAR 2021.0 11 252 42 335.0 6.0 7.98 55.83 42.0 101 40.08 33 12 1/16
B KUMAR 2022.0 14 313 53 383.0 12.0 7.23 31.92 26.08 129 41.21 31 12 3/22
B KUMAR 2023.0 14 306 51 425.0 16.0 8.33 26.56 19.12 121 39.54 50 11 5/30
B KUMAR 2024.0 16 342 57 533.0 11.0 9.35 48.45 31.09 126 36.84 62 21 3/41
B KUMAR 2025.0 14 312 52 483.0 17.0 9.29 28.41 18.35 116 37.18 46 26 3/33

In [45]:
agg_player_bowling_table = pd.DataFrame()
agg_player_bowling_table["player_id"] = player_id_col
agg_player_bowling_table["season_id"] = season_id_col
agg_player_bowling_table["matches"] = matches_col
agg_player_bowling_table["innings"] = innings_col
agg_player_bowling_table["balls_bowled"] = balls_bowled_col
agg_player_bowling_table["overs"] = overs_col
agg_player_bowling_table["runs_conceded"] = runs_conceded_col
agg_player_bowling_table["wickets"] = wickets_col
agg_player_bowling_table["economy"] = economy_col
agg_player_bowling_table["bowling_average"] = bowling_avg_col
agg_player_bowling_table["bowling_strike_rate"] = bowling_sr_col
agg_player_bowling_table["dot_balls"] = dot_balls_col
agg_player_bowling_table["dot_balls_pct"] = dot_balls_pct_col
agg_player_bowling_table["fours_conceded"] = fours_conceded_col
agg_player_bowling_table["sixes_conceded"] = sixes_conceded_col
agg_player_bowling_table["best_bowling_figures"] = best_bowling_figs_col

In [46]:
agg_player_bowling_table.head()

,player_id,season_id,matches,innings,balls_bowled,overs,runs_conceded,wickets,economy,bowling_average,bowling_strike_rate,dot_balls,dot_balls_pct,fours_conceded,sixes_conceded,best_bowling_figures
0,455,5,9,9,163,28,237.0,11.0,8.46,21.55,14.82,55,33.74,14,12,3/25
1,455,6,5,5,40,7,70.0,3.0,10.00,23.33,13.33,10,25.00,7,3,1/7
2,455,8,4,4,36,6,50.0,3.0,8.33,16.67,12.00,9,25.00,1,3,1/11
3,455,9,2,2,23,4,39.0,1.0,9.75,39.00,23.00,5,21.74,4,2,1/14
4,144,15,2,2,12,2,11.0,2.0,5.50,5.50,6.00,3,25.00,0,0,1/5

In [47]:
agg_player_bowling_table.to_csv("database-tables/agg-player-bowling-table.csv",index=False)

### Agg Team Table

In [48]:
team_id_col = []
season_id_col = []
matches_col = []
wins_col = []
losses_col = []
ties_col = []
no_results_col = []
win_pct_col = []
runs_scored_col = []
runs_conceded_col = []
wickets_taken_col = []
wickets_lost_col = []
avg_runs_scored_col = []
avg_runs_conceded_col = []
chasing_matches_col = []
chasing_wins_col = []
chasing_win_pct_col = []
defending_matches_col = []
defending_wins_col = []
defending_win_pct_col = []
fours_col = []
sixes_col = []


season_map = season_dim_table.set_index("season")["season_id"]
team_map = team_dim_table.set_index("team_name")["team_id"]

for team in team_dim_table["team_name"].unique():
    for season in season_dim_table["season"].unique():

        values = cleaned_ipl_data[(cleaned_ipl_data["season"]==season) & ((cleaned_ipl_data["batting_team"]==team) | (cleaned_ipl_data["bowling_team"]==team))]

        if values.shape[0]==0:
            continue
        
        # -------------------------------------------------------------
        #                       Calculate Values
        # -------------------------------------------------------------
        matches = values["match_id"].nunique()
        try:
            wins = values[["match_id","match_won_by"]].drop_duplicates()["match_won_by"].value_counts()[team]
        except KeyError:
            wins = 0

        try:
            ties = values[["match_id","result_type"]].drop_duplicates()["result_type"].value_counts()["TIE"]
        except KeyError:
            ties = 0

        try:
            no_results = values[["match_id","result_type"]].drop_duplicates()["result_type"].value_counts()["NO RESULT"]
        except KeyError:
            no_results = 0

        losses = matches - wins - ties - no_results
        # print(wins, matches)
        win_pct = round(wins/matches*100, 2)
        runs_scored = values[values["batting_team"]==team]["runs_total"].sum()
        runs_conceded = values[values["batting_team"]!=team]["runs_total"].sum()
        wicks_taken = values[values["batting_team"]!=team]["wicket_kind"].value_counts().sum()
        wicks_lost = values[values["batting_team"]==team]["wicket_kind"].value_counts().sum()
        avg_runs_scored = round(runs_scored/matches, 2)
        avg_runs_conceded = round(runs_conceded/matches, 2)


        chasing_matches = values[(values["innings"]%2==0) & (values["batting_team"]==team) ]["match_id"].nunique()
        chasing_ties_no_results = values[(values["innings"]%2==0) & (values["batting_team"]==team)  & (values["result_type"].isin(["TIE", "NO RESULT"]))]["match_id"].nunique()

        try:
            chasing_wins = values[(values["innings"]%2==0) & (values["batting_team"]==team)][["match_id","match_won_by"]].drop_duplicates()["match_won_by"].value_counts()[team]
        except KeyError:
            chasing_wins = 0
        
        chasing_win_pct = round((chasing_wins/(chasing_matches-chasing_ties_no_results))*100, 2)

        defending_matches = values[(values["innings"]%2!=0) & (values["batting_team"]==team) ]["match_id"].nunique()
        defending_ties_no_results = values[(values["innings"]%2!=0) & (values["batting_team"]==team)  & (values["result_type"].isin(["TIE", "NO RESULT"]))]["match_id"].nunique()

        try:
            defending_wins = values[(values["innings"]%2!=0) & (values["batting_team"]==team)][["match_id","match_won_by"]].drop_duplicates()["match_won_by"].value_counts()[team]
        except KeyError:
            defending_wins = 0

        defending_win_pct = round((defending_wins/(defending_matches-defending_ties_no_results))*100, 2)

        try:
            fours = values["runs_batter"].value_counts()[4]
        except:
            fours = 0

        try:
            sixes = values["runs_batter"].value_counts()[6]
        except:
            sixes = 0
        
        # -------------------------------------------------------------
        #                       Append Values
        # -------------------------------------------------------------
        team_id_col.append(team_map[team])
        season_id_col.append(season_map[season])
        matches_col.append(matches)
        wins_col.append(wins)
        losses_col.append(losses)
        ties_col.append(ties)
        no_results_col.append(no_results)
        win_pct_col.append(win_pct)
        runs_scored_col.append(runs_scored)
        runs_conceded_col.append(runs_conceded)
        wickets_taken_col.append(wicks_taken)
        wickets_lost_col.append(wicks_lost)
        avg_runs_scored_col.append(avg_runs_scored)
        avg_runs_conceded_col.append(avg_runs_conceded)
        chasing_matches_col.append(chasing_matches)
        chasing_wins_col.append(chasing_wins)
        chasing_win_pct_col.append(chasing_win_pct)
        defending_matches_col.append(defending_matches)
        defending_wins_col.append(defending_wins)
        defending_win_pct_col.append(defending_win_pct)
        fours_col.append(fours)
        sixes_col.append(sixes)

In [49]:
agg_team_table = pd.DataFrame()
agg_team_table["team_id"] = team_id_col
agg_team_table["season_id"] = season_id_col
agg_team_table["matches"] = matches_col
agg_team_table["wins"] = wins_col
agg_team_table["ties"] = ties_col
agg_team_table["no_results"] = no_results_col
agg_team_table["losses"] = losses_col
agg_team_table["win_pct"] = win_pct_col
agg_team_table["runs_scored"] = runs_scored_col
agg_team_table["runs_conceded"] = runs_conceded_col
agg_team_table["wickets_taken"] = wickets_taken_col
agg_team_table["wickets_lost"] = wickets_lost_col
agg_team_table["avg_runs_scored"] = avg_runs_scored_col
agg_team_table["avg_runs_conceded"] = avg_runs_conceded_col
agg_team_table["chasing_matches"] = chasing_matches_col
agg_team_table["chasing_wins"] = chasing_wins_col
agg_team_table["chasing_win_pct"] = chasing_win_pct_col
agg_team_table["defending_matches"] = defending_matches_col
agg_team_table["defending_wins"] = defending_wins_col
agg_team_table["defending_win_pct"] = defending_win_pct_col
agg_team_table["fours"] = fours_col
agg_team_table["sixes"] = sixes_col

In [50]:
agg_team_table.head()

,team_id,season_id,matches,wins,ties,no_results,losses,win_pct,runs_scored,runs_conceded,...,avg_runs_scored,avg_runs_conceded,chasing_matches,chasing_wins,chasing_win_pct,defending_matches,defending_wins,defending_win_pct,fours,sixes
0,1,9,14,5,0,0,9,35.71,2063.0,2113.0,...,147.36,150.93,7,5,71.43,7,0,0.00,343,143
1,1,10,16,10,0,0,6,62.50,2470.0,2436.0,...,154.38,152.25,8,5,62.50,8,5,62.50,394,186
2,2,15,16,12,0,0,4,75.00,2663.0,2534.0,...,166.44,158.38,9,8,88.89,7,4,57.14,468,180
3,2,16,17,11,0,0,6,64.71,3054.0,2840.0,...,179.65,167.06,9,6,66.67,8,5,62.50,491,257
4,2,17,12,5,0,0,7,41.67,2040.0,2101.0,...,170.00,175.08,6,3,50.00,6,2,33.33,357,177

In [51]:
agg_team_table.to_csv("database-tables/agg-team-table.csv",index=False)

### Agg Venue Table

In [52]:
venue_id_col = []
season_id_col = []
matches_col = []
avg_first_innings_score_col = []
avg_second_innings_score_col = []
highest_total_col = []
lowest_total_col = []
highest_total_chased_col = []
batting_first_wins_col = []
batting_second_wins_col = []
batting_first_win_pct_col = []
batting_second_win_pct_col = []
avg_wickets_col = []
fours_col = []
sixes_col = []

season_map = season_dim_table.set_index("season")["season_id"]
venue_map = venue_dim_table.set_index("venue")["venue_id"]

for stadium in venue_dim_table["venue"].unique():
    for season in season_dim_table["season"].unique():

        
        values = cleaned_ipl_data[(cleaned_ipl_data["venue"]==stadium) & (cleaned_ipl_data["season"]==season)]

        if values.empty:
            continue


        matches = values["match_id"].nunique()

        values = values[(~values["result_type"].isin(["TIE", "NO RESULT"]))]

        first_innings_scores = values[values["innings"]==1].groupby(["match_id"])["runs_total"].sum().values.tolist()
        second_innings_scores = values[values["innings"]==2].groupby(["match_id"])["runs_total"].sum().values.tolist()

        avg_first_innings_score = round(np.mean(first_innings_scores),2)
        avg_second_innings_score = round(np.mean(second_innings_scores),2)

        successful_chases = [
            second
            for first, second in zip(first_innings_scores, second_innings_scores)
            if second > first
        ]
        highest_total_chased = max(successful_chases) if successful_chases else None

        batting_first_wins = sum(
            first > second
            for first, second in zip(first_innings_scores, second_innings_scores)
        )

        batting_second_wins = sum(
            second > first
            for first, second in zip(first_innings_scores, second_innings_scores)
        )

        batting_first_win_pct = round((batting_first_wins/matches)*100,2)
        batting_second_win_pct = round((batting_second_wins/matches)*100,2)

        highest_total = max(first_innings_scores+second_innings_scores)
        lowest_total = min(first_innings_scores+second_innings_scores)

        wickets = values.groupby(["match_id", "batting_team"])["wicket_kind"].count().tolist()
        avg_wickets = round(np.mean(wickets))

        try:
            fours = values["runs_batter"].value_counts()[4]
        except:
            fours = 0

        try:
            sixes = values["runs_batter"].value_counts()[6]
        except:
            sixes = 0
        
        venue_id_col.append(venue_map[stadium])
        season_id_col.append(season_map[season])
        matches_col.append(matches)
        avg_first_innings_score_col.append(avg_first_innings_score)
        avg_second_innings_score_col.append(avg_second_innings_score)
        highest_total_col.append(highest_total)
        lowest_total_col.append(lowest_total)
        highest_total_chased_col.append(highest_total_chased)
        batting_first_wins_col.append(batting_first_wins)
        batting_second_wins_col.append(batting_second_wins)
        batting_first_win_pct_col.append(batting_first_win_pct)
        batting_second_win_pct_col.append(batting_second_win_pct)
        avg_wickets_col.append(avg_wickets)
        fours_col.append(fours)
        sixes_col.append(sixes)

In [53]:
agg_venue_table = pd.DataFrame()

agg_venue_table["venue_id"] = venue_id_col
agg_venue_table["season_id"] = season_id_col
agg_venue_table["matches"] = matches_col
agg_venue_table["avg_first_innings_score"] = avg_first_innings_score_col
agg_venue_table["avg_second_innings_score"] = avg_second_innings_score_col
agg_venue_table["highest_total"] = highest_total_col
agg_venue_table["lowest_total"] = lowest_total_col
agg_venue_table["highest_total_chased"] = highest_total_chased_col
agg_venue_table["batting_first_wins"] = batting_first_wins_col
agg_venue_table["batting_second_wins"] = batting_second_wins_col
agg_venue_table["batting_first_win_pct"] = batting_first_win_pct_col
agg_venue_table["batting_second_win_pct"] = batting_second_win_pct_col
agg_venue_table["avg_wickets"] = avg_wickets_col
agg_venue_table["fours"] = fours_col
agg_venue_table["sixes"] = sixes_col

In [54]:
agg_venue_table.to_csv("database-tables/agg-venue-table.csv",index=False)

### Agg Match Table

In [55]:
match_id_col = []
date_col = []
season_id_col = []
venue_id_col = []
batting_first_team_id_col = []
batting_second_team_id_col = []
first_innings_score_col = []
first_innings_wickets_col = []
second_innings_score_col = []
second_innings_wickets_col = []
winner_team_id_col = []
win_outcome_col = []
player_of_match_id_col = []
fours_col = []
sixes_col = []
powerplay_score_1_col = []
middle_score_1_col = []
death_score_1_col = []
powerplay_score_2_col = []
middle_score_2_col = []
death_score_2_col = []



for key,values in enriched_delivery_fact_table.groupby(["match_id"]):
    
    match_details = match_dim_table[match_dim_table["match_id"]==key[0]]
    delivery_details = delivery_fact_table[delivery_fact_table["match_id"]==key[0]]

    match_id = key[0]
    season_id = match_details["season_id"].iloc[0]
    venue_id = match_details["venue_id"].iloc[0]
    date = match_details["date"].iloc[0]

    try:
        batting_first_team_id = delivery_details[delivery_details["innings"]==1]["batting_team_id"].iloc[0]
    except:
        batting_first_team_id = None
    try:
        batting_second_team_id = delivery_details[delivery_details["innings"]==2]["batting_team_id"].iloc[0]
    except:
        batting_second_team_id = None
    try:
        first_innings_score = delivery_details[delivery_details["innings"]==1]["runs_total"].sum()
    except:
        first_innings_score = None
    try:
        second_innings_score = delivery_details[delivery_details["innings"]==2]["runs_total"].sum()
    except:
        second_innings_score = None

    try:
        first_innings_wickets = delivery_details[delivery_details["innings"]==1]["wicket_kind"].value_counts().sum()
    except:
        first_innings_wickets = None
    try:
        second_innings_wickets = delivery_details[delivery_details["innings"]==2]["wicket_kind"].value_counts().sum()
    except:
        second_innings_wickets = None
    
    winner_team_id = match_details["match_winner_id"].iloc[0]
    win_outcome = match_details["win_outcome"].iloc[0]
    if not win_outcome:
        win_outcome = match_details["result_type"].iloc[0]
    pom_id = match_details["player_of_match_id"].iloc[0]
    
    try:
        fours = delivery_details["runs_batter"].value_counts()[4]
    except:
        fours = 0

    try:
        sixes = delivery_details["runs_batter"].value_counts()[6]
    except:
        sixes = 0

    try:
        powerplay_score_1 = values[(values["innings"]==1) & (values["phase"]=="Powerplay Over")]["runs_total"].sum()
    except:
        powerplay_score_1 = None
    
    try:
        middle_score_1 = values[(values["innings"]==1) & (values["phase"]=="Middle Over")]["runs_total"].sum()
    except:
        middle_score_1 = None
    
    try:
        death_score_1 = values[(values["innings"]==1) & (values["phase"]=="Death Over")]["runs_total"].sum()
    except:
        death_score_1 = None
    
    try:
        powerplay_score_2 = values[(values["innings"]==2) & (values["phase"]=="Powerplay Over")]["runs_total"].sum()
    except:
        powerplay_score_2 = None
    
    try:
        middle_score_2 = values[(values["innings"]==2) & (values["phase"]=="Middle Over")]["runs_total"].sum()
    except:
        middle_score_2 = None
    
    try:
        death_score_2 = values[(values["innings"]==2) & (values["phase"]=="Death Over")]["runs_total"].sum()
    except:
        death_score_2 = None

    
    match_id_col.append(match_id)
    date_col.append(date)
    season_id_col.append(season_id)
    venue_id_col.append(venue_id)
    batting_first_team_id_col.append(batting_first_team_id)
    batting_second_team_id_col.append(batting_second_team_id)
    first_innings_score_col.append(first_innings_score)
    first_innings_wickets_col.append(first_innings_wickets)
    second_innings_score_col.append(second_innings_score)
    second_innings_wickets_col.append(second_innings_wickets)
    winner_team_id_col.append(winner_team_id)
    win_outcome_col.append(win_outcome)
    player_of_match_id_col.append(pom_id)
    fours_col.append(fours)
    sixes_col.append(sixes)
    powerplay_score_1_col.append(powerplay_score_1)
    middle_score_1_col.append(middle_score_1)
    death_score_1_col.append(death_score_1)
    powerplay_score_2_col.append(powerplay_score_2)
    middle_score_2_col.append(middle_score_2)
    death_score_2_col.append(death_score_2)

In [56]:
agg_match_table = pd.DataFrame()
agg_match_table["match_id"] = match_id_col
agg_match_table["date"] = date_col
agg_match_table["season_id"] = season_id_col
agg_match_table["venue_id"] = venue_id_col
agg_match_table["batting_first_team_id"] = batting_first_team_id_col
agg_match_table["batting_second_team_id"] = batting_second_team_id_col
agg_match_table["first_innings_score"] = first_innings_score_col
agg_match_table["first_innings_wickets"] = first_innings_wickets_col
agg_match_table["second_innings_score"] = second_innings_score_col
agg_match_table["second_innings_wickets"] = second_innings_wickets_col
agg_match_table["winner_team_id"] = winner_team_id_col
agg_match_table["win_outcome"] = win_outcome_col
agg_match_table["player_of_match_id"] = player_of_match_id_col
agg_match_table["fours"] = fours_col
agg_match_table["sixes"] = sixes_col
agg_match_table["powerplay_overs_score_1"] = powerplay_score_1_col
agg_match_table["middle_overs_score_1"] = middle_score_1_col
agg_match_table["death_overs_score_1"] = death_score_1_col
agg_match_table["powerplay_overs_score_2"] = powerplay_score_2_col
agg_match_table["middle_overs_score_2"] = middle_score_2_col
agg_match_table["death_overs_score_2"] = death_score_2_col

In [57]:
agg_match_table

,match_id,date,season_id,venue_id,batting_first_team_id,batting_second_team_id,first_innings_score,first_innings_wickets,second_innings_score,second_innings_wickets,...,win_outcome,player_of_match_id,fours,sixes,powerplay_overs_score_1,middle_overs_score_1,death_overs_score_1,powerplay_overs_score_2,middle_overs_score_2,death_overs_score_2
0,335982.0,2008-04-18,1,3,8,11.0,222.0,3,82.0,10,...,140 RUNS,718,18,17,61.0,93.0,68.0,26.0,55.0,1.0
1,335983.0,2008-04-19,1,8,7,15.0,240.0,5,207.0,4,...,33 RUNS,540,38,25,53.0,108.0,79.0,63.0,102.0,42.0
2,335984.0,2008-04-19,1,11,3,10.0,129.0,8,132.0,1,...,9 WICKETS,464,32,4,40.0,56.0,33.0,55.0,73.0,4.0
3,335985.0,2008-04-20,1,27,14,11.0,165.0,7,166.0,5,...,5 WICKETS,458,33,11,47.0,58.0,60.0,40.0,78.0,48.0
4,335986.0,2008-04-20,1,24,12,8.0,110.0,10,112.0,5,...,5 WICKETS,219,11,10,39.0,38.0,33.0,26.0,55.0,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,1473508.0,2025-05-29,18,7,16,9.0,101.0,10,106.0,2,...,8 WICKETS,593,18,9,48.0,53.0,0.0,61.0,45.0,0.0
1165,1473509.0,2025-05-30,18,7,14,2.0,228.0,5,208.0,6,...,20 RUNS,470,35,25,79.0,81.0,68.0,66.0,95.0,47.0
1166,1473510.0,2025-06-01,18,2,14,16.0,203.0,6,207.0,5,...,5 WICKETS,644,35,21,65.0,81.0,57.0,64.0,83.0,60.0
1167,1473511.0,2025-06-03,18,2,9,16.0,190.0,9,184.0,7,...,6 RUNS,99,19,23,55.0,77.0,58.0,52.0,67.0,65.0
1168,1485779.0,2025-05-24,18,19,16,6.0,206.0,8,208.0,4,...,6 WICKETS,436,35,21,60.0,82.0,64.0,61.0,94.0,53.0

In [58]:
agg_match_table.to_csv("database-tables/agg-match-table.csv",index=False)

### Agg Player VS Team Table

In [59]:
player_id_col = []
opposition_team_id_col = []
season_id_col = []
matches_col = []
innings_col = []
runs_col = []
balls_col = []
average_col = []
strike_rate_col = []
highest_score_col = []
fours_col = []
sixes_col = []
fifties_col = []
hundreds_col = []
dismissals_col = []
dot_ball_pct_col = []
boundary_pct_col = []

player_map = player_dim_table.set_index("player_name")["player_id"]
team_map = team_dim_table.set_index("team_name")["team_id"]
season_map = season_dim_table.set_index("season")["season_id"]

for key,values in cleaned_ipl_data.groupby(["batter","bowling_team", "season"]):
    player, opposition_team, season = key

    
    matches = values["match_id"].nunique()
    innings = values[["match_id","innings"]].drop_duplicates().shape[0]
    match_runs = values.groupby(["match_id"])["runs_batter"].sum().tolist()
    runs = sum(match_runs)
    balls = values["balls_faced"].sum()
    average = round(runs/matches, 2)
    strike_rate = round(runs/balls*100, 2)
    highest_score = max(match_runs)
    fifties = [i>=50 for i in match_runs].count(True)
    hundreds = [i>=100 for i in match_runs].count(True)
    dismissals = values["wicket_kind"].value_counts().sum()
    
    try:
        fours = values["runs_batter"].value_counts()[4]
    except:
        fours = 0

    try:
        sixes = values["runs_batter"].value_counts()[6]
    except:
        sixes = 0
    
    try:
        dot_balls_pct = round(values["runs_total"].value_counts()[0]/balls * 100, 2)
    except KeyError:
        dot_balls_pct = 0
    
    boundary_pct = round((fours+sixes)/balls*100, 2)

    player_id_col.append(player_map[player])
    opposition_team_id_col.append(team_map[opposition_team])
    season_id_col.append(season_map[season])
    matches_col.append(matches)
    innings_col.append(innings)
    runs_col.append(runs)
    balls_col.append(balls)
    average_col.append(average)
    strike_rate_col.append(strike_rate)
    highest_score_col.append(highest_score)
    fours_col.append(fours)
    sixes_col.append(sixes)
    fifties_col.append(fifties)
    hundreds_col.append(hundreds)
    dismissals_col.append(dismissals)
    dot_ball_pct_col.append(dot_balls_pct)
    boundary_pct_col.append(boundary_pct)

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\1353290962.py:33: RuntimeWarning: invalid value encountered in scalar divide
  strike_rate = round(runs/balls*100, 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\1353290962.py:54: RuntimeWarning: invalid value encountered in scalar divide
  boundary_pct = round((fours+sixes)/balls*100, 2)

In [60]:
agg_player_vs_team = pd.DataFrame()

agg_player_vs_team["player_id"] = player_id_col
agg_player_vs_team["opposition_team_id"] = opposition_team_id_col
agg_player_vs_team["season_id"] = season_id_col
agg_player_vs_team["matches"] = matches_col
agg_player_vs_team["innings"] = innings_col
agg_player_vs_team["runs"] = runs_col
agg_player_vs_team["balls"] = balls_col
agg_player_vs_team["average"] = average_col
agg_player_vs_team["strike_rate"] = strike_rate_col
agg_player_vs_team["highest_score"] = highest_score_col
agg_player_vs_team["fours"] = fours_col
agg_player_vs_team["sixes"] = sixes_col
agg_player_vs_team["fifties"] = fifties_col
agg_player_vs_team["hundreds"] = hundreds_col
agg_player_vs_team["dismissals"] = dismissals_col
agg_player_vs_team["dot_ball_pct"] = dot_ball_pct_col
agg_player_vs_team["boundary_pct"] = boundary_pct_col

In [61]:
agg_player_vs_team.sort_values(by=["highest_score"], ascending=False)

,player_id,opposition_team_id,season_id,matches,innings,runs,balls,average,strike_rate,highest_score,fours,sixes,fifties,hundreds,dismissals,dot_ball_pct,boundary_pct
1916,719,5,6,2,2,196.0,87.0,98.0,225.29,175.0,15,18,1,1,1,27.59,37.93
1635,718,11,1,1,1,158.0,73.0,158.0,216.44,158.0,10,13,1,1,0,23.29,31.51
469,334,16,18,1,1,141.0,55.0,141.0,256.36,141.0,14,10,1,1,1,18.18,43.64
7761,675,8,15,2,2,190.0,99.0,95.0,191.92,140.0,14,13,2,1,2,26.26,27.27
333,476,14,8,2,2,174.0,70.0,87.0,248.57,133.0,24,7,1,1,1,15.71,44.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11239,354,3,18,1,1,0.0,2.0,0.0,0.00,0.0,0,0,0,0,1,100.00,0.00
11236,230,11,15,1,1,0.0,1.0,0.0,0.00,0.0,0,0,0,0,1,100.00,0.00
11234,230,16,15,1,1,0.0,1.0,0.0,0.00,0.0,0,0,0,0,0,0.00,0.00
4290,159,7,17,1,1,0.0,1.0,0.0,0.00,0.0,0,0,0,0,1,100.00,0.00
12126,755,12,5,1,1,0.0,4.0,0.0,0.00,0.0,0,0,0,0,1,100.00,0.00

In [62]:
agg_player_vs_team.to_csv("database-tables/agg-player-vs-team-table.csv",index=False)

### Agg Player VS Venue Table

In [63]:
player_id_col = []
venue_id_col = []
season_id_col = []
matches_col = []
innings_col = []
runs_col = []
balls_col = []
average_col = []
strike_rate_col = []
highest_score_col = []
fours_col = []
sixes_col = []
fifties_col = []
hundreds_col = []
dismissals_col = []
dot_ball_pct_col = []
boundary_pct_col = []

player_map = player_dim_table.set_index("player_name")["player_id"]
venue_map = venue_dim_table.set_index("venue")["venue_id"]
season_map = season_dim_table.set_index("season")["season_id"]

for key,values in cleaned_ipl_data.groupby(["batter","venue", "season"]):
    
    player, venue, season = key
    matches = values["match_id"].nunique()
    innings = values[["match_id","innings"]].drop_duplicates().shape[0]
    match_runs = values.groupby(["match_id"])["runs_batter"].sum().tolist()
    runs = sum(match_runs)
    balls = values["balls_faced"].sum()
    average = round(runs/matches, 2)
    strike_rate = round(runs/balls*100, 2)
    highest_score = max(match_runs)
    fifties = [i>=50 for i in match_runs].count(True)
    hundreds = [i>=100 for i in match_runs].count(True)
    dismissals = values["wicket_kind"].value_counts().sum()
    
    try:
        fours = values["runs_batter"].value_counts()[4]
    except:
        fours = 0

    try:
        sixes = values["runs_batter"].value_counts()[6]
    except:
        sixes = 0
    
    try:
        dot_balls_pct = round(values["runs_total"].value_counts()[0]/balls * 100, 2)
    except KeyError:
        dot_balls_pct = 0
    
    boundary_pct = round((fours+sixes)/balls*100, 2)

    player_id_col.append(player_map[player])
    venue_id_col.append(venue_map[venue])
    season_id_col.append(season_map[season])
    matches_col.append(matches)
    innings_col.append(innings)
    runs_col.append(runs)
    balls_col.append(balls)
    average_col.append(average)
    strike_rate_col.append(strike_rate)
    highest_score_col.append(highest_score)
    fours_col.append(fours)
    sixes_col.append(sixes)
    fifties_col.append(fifties)
    hundreds_col.append(hundreds)
    dismissals_col.append(dismissals)
    dot_ball_pct_col.append(dot_balls_pct)
    boundary_pct_col.append(boundary_pct)

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\2514511329.py:32: RuntimeWarning: invalid value encountered in scalar divide
  strike_rate = round(runs/balls*100, 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\2514511329.py:53: RuntimeWarning: invalid value encountered in scalar divide
  boundary_pct = round((fours+sixes)/balls*100, 2)

In [64]:
agg_player_vs_venue = pd.DataFrame()

agg_player_vs_venue["player_id"] = player_id_col
agg_player_vs_venue["venue_id"] = venue_id_col
agg_player_vs_venue["season_id"] = season_id_col
agg_player_vs_venue["matches"] = matches_col
agg_player_vs_venue["innings"] = innings_col
agg_player_vs_venue["runs"] = runs_col
agg_player_vs_venue["balls"] = balls_col
agg_player_vs_venue["average"] = average_col
agg_player_vs_venue["strike_rate"] = strike_rate_col
agg_player_vs_venue["highest_score"] = highest_score_col
agg_player_vs_venue["fours"] = fours_col
agg_player_vs_venue["sixes"] = sixes_col
agg_player_vs_venue["fifties"] = fifties_col
agg_player_vs_venue["hundreds"] = hundreds_col
agg_player_vs_venue["dismissals"] = dismissals_col
agg_player_vs_venue["dot_ball_pct"] = dot_ball_pct_col
agg_player_vs_venue["boundary_pct"] = boundary_pct_col

In [65]:
agg_player_vs_venue

,player_id,venue_id,season_id,matches,innings,runs,balls,average,strike_rate,highest_score,fours,sixes,fifties,hundreds,dismissals,dot_ball_pct,boundary_pct
0,455,11,6,1,1,16.0,9.0,16.0,177.78,16.0,2,0,0,0,1,11.11,22.22
1,455,38,8,2,2,28.0,17.0,14.0,164.71,15.0,1,2,0,0,1,17.65,17.65
2,455,24,6,1,1,4.0,5.0,4.0,80.00,4.0,0,0,0,0,1,40.00,0.00
3,455,3,6,1,1,3.0,4.0,3.0,75.00,3.0,0,0,0,0,1,25.00,0.00
4,455,3,9,1,1,32.0,18.0,32.0,177.78,32.0,2,3,0,0,1,38.89,27.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10898,755,8,1,1,1,1.0,4.0,1.0,25.00,1.0,0,0,0,0,0,50.00,0.00
10899,755,8,3,1,1,0.0,1.0,0.0,0.00,0.0,0,0,0,0,1,100.00,0.00
10900,755,17,4,1,1,0.0,3.0,0.0,0.00,0.0,0,0,0,0,1,100.00,0.00
10901,755,17,5,1,1,0.0,4.0,0.0,0.00,0.0,0,0,0,0,1,100.00,0.00
10902,755,19,1,1,1,1.0,5.0,1.0,20.00,1.0,0,0,0,0,1,80.00,0.00

In [66]:
agg_player_vs_venue.to_csv("database-tables/agg-player-vs-venue-table.csv",index=False)

### Agg Player Phase Table

In [67]:
player_id_col = []
season_id_col = []
phase_col = []
matches_col = []
innings_col = []
runs_col = []
balls_col = []
average_col = []
strike_rate_col = []
highest_score_col = []
fours_col = []
sixes_col = []
dismissals_col = []
dot_ball_pct_col = []
boundary_pct_col = []

for season_id,vals in match_dim_table.groupby(["season_id"]):
    
    match_ids = vals['match_id']
    season_id = season_id[0]
    print(f" Found {len(match_ids)} matches for IPL season {season_id}")

    for key,values in enriched_delivery_fact_table[enriched_delivery_fact_table["match_id"].isin(match_ids)].groupby(["batter_id","phase"]):
    
    
        player_id, phase = key

        matches = values["match_id"].nunique()
        innings = values[["match_id","innings"]].drop_duplicates().shape[0]
        match_runs = values.groupby(["match_id"])["runs_batter"].sum().tolist()
        runs = sum(match_runs)
        balls = values["batter_balls"].shape[0]
        average = round(runs/matches, 2)
        strike_rate = round(runs/balls*100, 2)
        highest_score = max(match_runs)
        dismissals = values["wicket_kind"].value_counts().sum()
        
        try:
            fours = values["runs_batter"].value_counts()[4]
        except:
            fours = 0

        try:
            sixes = values["runs_batter"].value_counts()[6]
        except:
            sixes = 0
        
        try:
            dot_balls_pct = round(values["runs_total"].value_counts()[0]/balls * 100, 2)
        except KeyError:
            dot_balls_pct = 0
        
        boundary_pct = round((fours+sixes)/balls*100, 2)

        player_id_col.append(player_id)
        season_id_col.append(season_id)
        phase_col.append(phase)
        matches_col.append(matches)
        innings_col.append(innings)
        runs_col.append(runs)
        balls_col.append(balls)
        average_col.append(average)
        strike_rate_col.append(strike_rate)
        highest_score_col.append(highest_score)
        fours_col.append(fours)
        sixes_col.append(sixes)
        dismissals_col.append(dismissals)
        dot_ball_pct_col.append(dot_balls_pct)
        boundary_pct_col.append(boundary_pct)

 Found 116 matches for IPL season 1
 Found 114 matches for IPL season 2
 Found 120 matches for IPL season 3
 Found 145 matches for IPL season 4
 Found 148 matches for IPL season 5
 Found 152 matches for IPL season 6
 Found 120 matches for IPL season 7
 Found 117 matches for IPL season 8
 Found 120 matches for IPL season 9
 Found 118 matches for IPL season 10
 Found 120 matches for IPL season 11
 Found 120 matches for IPL season 12
 Found 120 matches for IPL season 13
 Found 120 matches for IPL season 14
 Found 148 matches for IPL season 15
 Found 147 matches for IPL season 16
 Found 142 matches for IPL season 17
 Found 146 matches for IPL season 18

In [68]:
agg_player_vs_phase = pd.DataFrame()

agg_player_vs_phase["player_id"] = player_id_col
agg_player_vs_phase["season_id"] = season_id_col
agg_player_vs_phase["phase"] = phase_col
agg_player_vs_phase["matches"] = matches_col
agg_player_vs_phase["innings"] = innings_col
agg_player_vs_phase["runs"] = runs_col
agg_player_vs_phase["balls"] = balls_col
agg_player_vs_phase["average"] = average_col
agg_player_vs_phase["strike_rate"] = strike_rate_col
agg_player_vs_phase["highest_score"] = highest_score_col
agg_player_vs_phase["fours"] = fours_col
agg_player_vs_phase["sixes"] = sixes_col
agg_player_vs_phase["dismissals"] = dismissals_col
agg_player_vs_phase["dot_ball_pct"] = dot_ball_pct_col
agg_player_vs_phase["boundary_pct"] = boundary_pct_col

In [69]:
agg_player_vs_phase

,player_id,season_id,phase,matches,innings,runs,balls,average,strike_rate,highest_score,fours,sixes,dismissals,dot_ball_pct,boundary_pct
0,1,1,Death Over,2,2,4.0,5,2.00,80.00,4.0,1,0,1,80.00,20.00
1,7,1,Death Over,2,2,27.0,21,13.50,128.57,14.0,2,1,2,23.81,14.29
2,7,1,Middle Over,8,8,77.0,78,9.62,98.72,34.0,6,1,6,25.64,8.97
3,7,1,Powerplay Over,8,8,95.0,89,11.88,106.74,30.0,15,2,3,51.69,19.10
4,14,1,Middle Over,4,4,76.0,58,19.00,131.03,28.0,10,1,3,29.31,18.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5852,770,18,Powerplay Over,7,7,84.0,46,12.00,182.61,25.0,7,7,2,39.13,30.43
5853,770,18,Super Over,1,1,4.0,2,4.00,200.00,4.0,1,0,1,50.00,50.00
5854,778,18,Death Over,2,2,53.0,21,26.50,252.38,49.0,8,2,2,14.29,47.62
5855,778,18,Middle Over,6,6,85.0,75,14.17,113.33,41.0,7,2,4,32.00,12.00
5856,778,18,Powerplay Over,2,2,4.0,11,2.00,36.36,3.0,0,0,1,72.73,0.00

In [70]:
agg_player_vs_phase.to_csv("database-tables/agg-player-vs-phase-table.csv",index=False)

### Agg Bowler Phase Table

In [71]:
player_id_col = []
season_id_col = []
phase_col = []
matches_col = []
innings_col = []
balls_bowled_col = []
overs_col = []
runs_conceded_col = []
wickets_col = []
economy_col = []
bowling_avg_col = []
bowling_sr_col = []
dot_balls_col = []
dot_ball_pct_col = []
fours_conceded_col = []
sixes_conceded_col = []

for season_id,vals in match_dim_table.groupby(["season_id"]):
    
    match_ids = vals['match_id']
    season_id = season_id[0]
    print(f" Found {len(match_ids)} matches for IPL season {season_id}")

    for key,values in enriched_delivery_fact_table[enriched_delivery_fact_table["match_id"].isin(match_ids)].groupby(["bowler_id","phase"]):
    
    
        player_id, phase = key

        matches = values["match_id"].nunique()
        innings = values[["match_id","innings"]].drop_duplicates().shape[0]
        balls_bowled = values["batter_balls"].shape[0]
        overs = np.floor(balls_bowled/6)
        match_runs = values.groupby(["match_id"])["runs_bowler"].sum().tolist()
        runs_conceded = sum(match_runs)
        try:
            wickets = values["is_bowler_wicket"].value_counts()[True]
        except:
            wickets = 0
        
        economy = round(runs_conceded/overs, 2)
        
        try:
            bowling_avg = round(runs_conceded/wickets, 2)
        except ZeroDivisionError:
            bowling_avg = 0
        try:
            legal_balls_bowled = values["valid_ball"].value_counts()[True]
        except KeyError:
            legal_balls_bowled = 0
        try:
            bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
        except ZeroDivisionError:
            bowling_strike_rate = 0
        
        try:
            fours_conceded = values["runs_batter"].value_counts()[4]
        except:
            fours_conceded = 0

        try:
            sixes_conceded = values["runs_batter"].value_counts()[6]
        except:
            sixes_conceded = 0
        
        try:
            dot_balls = values["runs_total"].value_counts()[0]
            dot_balls_pct = round(dot_balls/balls_bowled * 100, 2)
        except KeyError:
            dot_balls = 0
            dot_balls_pct = 0
        

        player_id_col.append(player_id)
        season_id_col.append(season_id)
        phase_col.append(phase)
        matches_col.append(matches)
        innings_col.append(innings)
        balls_bowled_col.append(balls_bowled)
        overs_col.append(overs)
        runs_conceded_col.append(runs_conceded)
        wickets_col.append(wickets)
        economy_col.append(economy)
        bowling_avg_col.append(bowling_avg)
        bowling_sr_col.append(bowling_strike_rate)
        dot_balls_col.append(dot_balls)
        dot_ball_pct_col.append(dot_balls_pct)
        fours_conceded_col.append(fours_conceded)
        sixes_conceded_col.append(sixes_conceded)

 Found 116 matches for IPL season 1

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 114 matches for IPL season 2
 Found 120 matches for IPL season 3

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)

 Found 145 matches for IPL season 4

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 148 matches for IPL season 5

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 152 matches for IPL season 6

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: invalid value encountered in scalar divide
  economy = round(runs_conceded/overs, 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 120 matches for IPL season 7

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 117 matches for IPL season 8

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 120 matches for IPL season 9

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 118 matches for IPL season 10

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 120 matches for IPL season 11

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 120 matches for IPL season 12

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: invalid value encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 120 matches for IPL season 13

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 120 matches for IPL season 14

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 148 matches for IPL season 15

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 147 matches for IPL season 16

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: invalid value encountered in scalar divide
  economy = round(runs_conceded/overs, 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

 Found 142 matches for IPL season 17

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)

 Found 146 matches for IPL season 18

C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:51: RuntimeWarning: divide by zero encountered in scalar divide
  bowling_strike_rate = round((legal_balls_bowled/wickets), 2)
C:\Users\darsh\AppData\Local\Temp\ipykernel_18244\553205335.py:40: RuntimeWarning: divide by zero encountered in scalar divide
  economy = round(runs_conceded/overs, 2)

In [72]:
agg_bowler_vs_phase = pd.DataFrame()

agg_bowler_vs_phase["player_id"] = player_id_col
agg_bowler_vs_phase["season_id"] = season_id_col
agg_bowler_vs_phase["phase"] = phase_col
agg_bowler_vs_phase["matches"] = matches_col
agg_bowler_vs_phase["innings"] = innings_col
agg_bowler_vs_phase["balls_bowled"] = balls_bowled_col
agg_bowler_vs_phase["overs"] = overs_col
agg_bowler_vs_phase["runs_conceded"] = runs_conceded_col
agg_bowler_vs_phase["wickets"] = wickets_col
agg_bowler_vs_phase["economy"] = economy_col
agg_bowler_vs_phase["bowling_avg"] = bowling_avg_col
agg_bowler_vs_phase["bowling_strike_rate"] = bowling_sr_col
agg_bowler_vs_phase["dot_balls"] = dot_balls_col
agg_bowler_vs_phase["dot_balls_pct"] = dot_ball_pct_col
agg_bowler_vs_phase["fours_conceded"] = fours_conceded_col
agg_bowler_vs_phase["sixes_conceded"] = sixes_conceded_col

In [73]:
agg_bowler_vs_phase

,player_id,season_id,phase,matches,innings,balls_bowled,overs,runs_conceded,wickets,economy,bowling_avg,bowling_strike_rate,dot_balls,dot_balls_pct,fours_conceded,sixes_conceded
0,1,1,Death Over,11,11,79,13.0,118.0,3,9.08,39.33,26.00,17,21.52,11,4
1,1,1,Middle Over,3,3,24,4.0,28.0,1,7.00,28.00,24.00,9,37.50,4,0
2,1,1,Powerplay Over,14,14,226,37.0,211.0,8,5.70,26.38,27.75,127,56.19,26,6
3,2,1,Death Over,1,1,6,1.0,10.0,0,10.00,0.00,inf,3,50.00,2,0
4,2,1,Middle Over,2,2,18,3.0,31.0,1,10.33,31.00,18.00,5,27.78,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5182,770,18,Death Over,1,1,8,1.0,13.0,0,13.00,0.00,inf,1,12.50,0,1
5183,770,18,Middle Over,9,9,114,19.0,151.0,3,7.95,50.33,36.00,25,21.93,8,6
5184,770,18,Powerplay Over,1,1,6,1.0,6.0,0,6.00,0.00,inf,3,50.00,1,0
5185,779,18,Death Over,5,5,25,4.0,50.0,0,12.50,0.00,inf,5,20.00,6,2
5186,779,18,Middle Over,10,10,184,30.0,283.0,6,9.43,47.17,30.00,42,22.83,18,15

In [74]:
agg_bowler_vs_phase.to_csv("database-tables/agg-bowler-vs-phase-table.csv",index=False)